"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Navbar;
var link_1 = require("next/link");
function Navbar() {
    return (React.createElement(React.Fragment, null,
        React.createElement("nav", { className: "flex justify-between bg-gray-100" },
            React.createElement("ul", { className: "flex gap-3" },
                React.createElement("li", { className: "" },
                    React.createElement(link_1.default, { href: "#" }, "Jordan")),
                React.createElement("li", { className: "" },
                    React.createElement(link_1.default, { href: "#" }, "Converse"))),
            React.createElement("ul", { className: "flex gap-3" },
                React.createElement("li", { className: "" },
                    React.createElement(link_1.default, { href: "#" }, "Find a Store")),
                React.createElement("li", { className: "" },
                    React.createElement(link_1.default, { href: "#" }, "Help")),
                React.createElement("li", { className: "" },
                    React.createElement(link_1.default, { href: "#" }, "Join Us")),
                React.createElement("li", { className: "" },
                    React.createElement(link_1.default, { href: "#" }, "Sign In")))),
        React.createElement("nav", { className: "flex justify-between" },
            React.createElement(link_1.default, { href: "" }, "Home"),
            React.createElement("ul", { className: "flex gap-3" },
                React.createElement("li", null,
                    React.createElement(link_1.default, { href: "#" }, "New")),
                React.createElement("li", null,
                    React.createElement(link_1.default, { href: "#" }, "Men")),
                React.createElement("li", null,
                    React.createElement(link_1.default, { href: "#" }, "Women")),
                React.createElement("li", null,
                    React.createElement(link_1.default, { href: "#" }, "Kids")),
                React.createElement("li", null,
                    React.createElement(link_1.default, { href: "#" }, "Jordan")),
                React.createElement("li", null,
                    React.createElement(link_1.default, { href: "#" }, "Sale"))),
            React.createElement("ul", { className: "flex gap-3" },
                React.createElement("li", null,
                    React.createElement("input", { type: "text" }),
                    "Search"),
                React.createElement("li", null,
                    React.createElement(link_1.default, { href: "#" }, "Favorites")),
                React.createElement("li", null,
                    React.createElement(link_1.default, { href: "app/cart/page.tsx" }, "Cart"))))));
}
